### ISSUE TITLE
plugin with id' com.andriod.library

### ISSUE THREAD

**Issue by Alicxx** [frostney/react-native-create-library#20] opened 2016-10-17 20:15 UTC
looking for a answer for the the plugin with id' com.andriod.library

apply plugin: 'com.android.library'

android {
    compileSdkVersion 23
    buildToolsVersion "24.0.3"

```
defaultConfig {
    minSdkVersion 21
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
    debug {
        testCoverageEnabled true
    }
}
```

}

apply plugin: 'jacoco'
jacoco {
    version "0.7.1.201405082137"
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile files('libs/AMZNMediaPlayer.jar')
    compile files('libs/exoplayer.jar')
    compile project(':ModuleInterface')
    compile project(':UAMP')

```
// Set this dependency to use JUnit 4 rules
androidTestCompile 'com.android.support.test:rules:0.4.1'

androidTestCompile('com.android.support.test:runner:0.4.1') {
    exclude module: 'support-annotations'
}
```

}

**Comment by frostney** [comment] 2017-02-23 00:37
Hi @Alicxx, I'm sorry for just replying to this now. By the current description I would assume this is a duplicate of #12.

If you don't think it is, feel free to re-open this issue and provide more information on the issue.

**Closed by frostney** 2017-02-23 00:37 UTC
